version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  default: standard

  settings:
    staticcheck:
      # Disable some noisy checks for legacy code
      checks:
        - "-ST1005"  # Error string capitalization

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
